### ISSUE TITLE
App doesn't serve uploaded images in production

### ISSUE THREAD

**Issue by Constuelo** [wsvincent/djangoforprofessionals#31] opened 2019-12-28 18:41 UTC
I don't have much information to give apart from the images 404

This is after you create a new book / upload an image.

Other static assets work as usual

Does anyone have any ideas? Or come across this, I'm pretty certain my code matches

**Comment by Constuelo** [comment] 2019-12-28 20:21
This is after completing every chapter in the book

**Comment by wsvincent** [comment] 2019-12-31 13:46
Hi @Constuelo this is an error that has been fixed in the updated version of the book. The issue is that WhiteNoise [won't serve media files in production](http://whitenoise.evans.io/en/stable/django.html#serving-media-files), so you need to use [django-storages](https://django-storages.readthedocs.io/en/latest/) to do that.

**Closed by wsvincent** 2019-12-31 13:46 UTC

**Comment by Constuelo** [comment] 2019-12-31 14:12
Thanks I solved the issue using AWS S3
